### ISSUE TITLE
Is GENTEMP necessary there?

### ISSUE THREAD

**Issue by phoe** [digikar99/polymorphic-functions#3]
https://github.com/digikar99/polymorphic-functions/blob/7e0161bf6bf5bc47c0ff468151f481956cc91166/src/dispatch.lisp#L160-L162

Why not just `gensym`?

**Comment by digikar99** [comment]
In the case of non-inline static-dispatch, the call to polymorphic-functions are substituted with the call to appropriate fbound-symbols. IIUC (and assuming I'm testing correctly), the symbols being gensyms do not provide the guarantee that the appropriate function would be called, especially when compiled-files are loaded. ([You know better words for this phenomenon.](https://github.com/Clozure/ccl/issues/352#issuecomment-752204911)) Essentially:

```lisp
POLYMORPHIC-FUNCTIONS> (eq '#:|(POLYMORPH FOO (STRING))0|
                           '#:|(POLYMORPH FOO (STRING))0|)
NIL
POLYMORPHIC-FUNCTIONS> (define-polymorphic-function foo (a) :overwrite t)
#<POLYMORPHIC-FUNCTION FOO (0)>
POLYMORPHIC-FUNCTIONS> (defpolymorph (foo :inline :maybe) ((a string)) t
  a)
FOO
POLYMORPHIC-FUNCTIONS> (defpolymorph (foo :inline :maybe) ((a string)) t a)
FOO
POLYMORPHIC-FUNCTIONS> (defun foo-caller (a)
                         (declare (optimize speed)
                                  (type string a))
                         (foo a))
WARNING: redefining POLYMORPHIC-FUNCTIONS::FOO-CALLER in DEFUN
FOO-CALLER
POLYMORPHIC-FUNCTIONS> (disassemble 'foo-caller) ; see the HERE marker
; disassembly for FOO-CALLER
; Size: 17 bytes. Origin: #x53AC937F                          ; FOO-CALLER
; 7F:       B902000000       MOV ECX, 2
; 84:       FF7508           PUSH QWORD PTR [RBP+8]
; 87:       B822E44550       MOV EAX, #x5045E422              ; #<FDEFN #:|(POLYMORPH FOO (STRING))0|> ; <=== HERE
; 8C:       FFE0             JMP RAX
; 8E:       CC10             INT3 16                          ; Invalid argument count trap
NIL
```

**Comment by phoe** [comment]
One problem with `gentemp` is that it might work really weird when you compile different files. `gentemp` is guaranteed to intern a new symbol *only* taking the current Lisp image into account, which means that if you use `gentemp` while compiling file A, restart your image, use `gentemp` while compiling file B, and then try to load both of those files, then a symbol collision is possible.

Have you tried using gensyms with `load-time-value` instead, to ensure that symbols are generated only when the respective FASL is loaded and not dumped into FASLs?

**Comment by digikar99** [comment]
I haven't quite wrapped my head around `load-time-value` or `make-load-form`; so, will need some time to think that way through.

But, about symbol collision: in this particular case IIUC, a symbol collision requires (necessary but not sufficient) that both `name` and `type-list` of the two symbols/polymorphs be the same. And when name and type-list are the same, we actually want the collision to take place; otherwise we'd be having multiple symbols referring to different definitions - some older, some newer - of the same polymorph. (EDIT) The non-collision is an issue even as things stand the way they are at the moment. `intern` seems like a way out instead; but we still need to account for two `type-list` referring to the same polymorph but not being `equal` themselves.

**Comment by digikar99** [comment]
The part/check before the gentemp exists so that users are not required to recompile usages for already-static-dispatched pfs on the mere redefinition of an existing polymorph.

If we were to go the gensym/gentemp way, there would more likely be two symbols with distinct suffix for the two files compiled in the context of two separate images. An `intern` can avoid that issue. But again, gensym feels like a cleaner method since it avoids the `polymorphic-functions.nonuser` package. I'm not sure how big of an issue the two symbol problem is. Ah, and there's `make-symbol` as well.

***

By the use of `load-time-value` in this context, do you mean `(load-time-value (fdefinition static-dispatch-name))`? Just tested this; did not "work"; `(fdefinition (load-time-value static-dispatch-name))` also failed to "work". Both of these cases lead to a undefined-function error.

By work, I'm referring to whether the compilation of these forms individually using `slime-compile-defun` results in a successful `(foo-caller "")` call, with appropriate changes to `defpolymorph` and `pf-compiler-macro`:

```lisp
(define-polymorphic-function foo (a) :overwrite t)

(defpolymorph (foo :inline :maybe) ((a string)) t
  a)

(defun foo-caller (a)
  (declare (optimize speed)
           (type string a))
  (foo a))
```

***

About `make-load-form`: did you intend to specialize it on the symbol class? Doing so feels a bit dirty to me; and I'm not sure in what contexts I should expect this to be called:

```lisp
(defmethod make-load-form ((s symbol) &optional env)
  (declare (ignore env))
  (if (symbol-package s)
      s
      (print `(progn
                (setf (fdefinition s) (lambda () 'hello))
                s))))
```

**Comment by phoe** [comment]
`defmethod make-load-form ((s symbol)` is illegal since it's a standard method with all-standard specializers.

I'll possibly rethink this and get back to you - I don't know if the issue I raised is actually correct in this system's context.

**Comment by digikar99** [comment]
Alright, would be glad to know if something occurs to you!

***

> The non-collision is an issue even as things stand the way they are at the moment.

Turns out the [ensure-unambiguous-call](https://github.com/digikar99/polymorphic-functions/blob/2b2c59c874d1c288c1bd5498d4975f405f77b302/src/dispatch.lisp#L75) takes care of this; I might modify this a bit, but the requirement for type-lists of two "equivalent" polymorphs be `equal` ensures that the static-dispatch-name would turn out to be the same with `intern`.
