### ISSUE TITLE
FLET as a NLAMBDA replacement

### ISSUE THREAD

**Issue by phoe** [digikar99/polymorphic-functions#4]
https://github.com/digikar99/polymorphic-functions/blob/7e0161bf6bf5bc47c0ff468151f481956cc91166/src/dispatch.lisp#L178-L184

You can use `(labels ((name ...)) #'name)` (or `flet`) instead of a fully anonymous function - multiple implementations will show the local name in the backtraces. See e.g.  https://github.com/phoe/trivial-custom-debugger/blob/a560594a673bbcd88136af82086107ee5ff9ca81/trivial-custom-debugger.lisp#L39-L40

**Comment by digikar99** [comment]
Right! I had originally started out with `(alexandria:named-lambda name ...)`, but that posed an issue for recursive functions. But instead of `name`, I later went with `(polymorph ,name ,type-list)`; so `alexandria:named-lambda` looks useable now, but I'll stick with FLET I guess:

Does this look good?

```lisp
(named-lambda ,(intern (write-to-string `(polymorph ,name ,type-list))
                       (symbol-package block-name))
  ,param-list
  ,(lambda-declarations parameters)
  ,declarations
  (block ,block-name
    ,@(butlast body)
    ,(ensure-type-form return-type (lastcar body))))
```

**Comment by phoe** [comment]
Sure, seems good to me.

**Comment by digikar99** [comment]
Thanks for the review!
