### ISSUE TITLE
Can I create my own types for parametric polymorphism?

### ISSUE THREAD

**Issue by shamazmazum** [digikar99/polymorphic-functions#5]
I want to create a type for dual numbers and define math functions for it (I suppose I can use `polymorph.maths` for this purpose). Can I create a type like this example in Haskell? I need something like a structure or cons pair with elements of type `a`.

I suppose that `(deftype dual (a) (list 'cons a))` will not work as this is just an alias for any cons with elements of type `a`, not a new special type for dual numbers. Am I right?

~~~~
data DualNum a = DualNum a a
    deriving(Show, Eq)

instance (Num a) => Num (DualNum a) where
    (DualNum x1 y1) + (DualNum x2 y2) = DualNum (x1 + x2) (y1 + y2)
    (DualNum x1 y1) * (DualNum x2 y2) = DualNum (x1 * x2) (x1 * y2 + x2 * y1)
    negate (DualNum x y) = DualNum (- x) (- y)
    fromInteger x = DualNum (fromInteger x) 0

instance (Fractional a) => Fractional (DualNum a) where
    (DualNum x1 y1) / (DualNum x2 y2) = DualNum (x1/x2) ((x2*y1 - x1*y2)/x2^2)

instance (Floating a) => Floating (DualNum a) where
    sin (DualNum x y) = DualNum (sin x) (y * (cos x))
    cos (DualNum x y) = DualNum (cos x) (y * (- (sin x)))
    exp (DualNum x y) = DualNum (exp x) (y * (exp x))
    log (DualNum x y) = DualNum (log x) (y / x)
~~~~

**Comment by digikar99** [comment]
I guess one of the main goals here is to write a generic `dual` type/structure/class with its contents varying from `(unsigned-byte 8)` all the way up to `complex` - correct me if I get it wrong.

I doubt polymorphic-functions could be much helpful for defining parametric-types themselves; OTOH it can be useful for defining optimizing / type-checking functions that can operate on those types. As in, once you have the types, you could write just a single add, multiply, negate, etc function which can be optimized for each of the types by incorporating the declarations at the call-site. The distinction perhaps does not even make sense in the Haskell world.

About parametric-types themselves, I'm out of time at the moment, so hope to get back later. A few pointers include:

- [cl-parametric-types](https://github.com/cosmos72/cl-parametric-types): I wonder if this can be integrated into PF and if so how.
- An attempt to define some parametric-types is in [polymorph.data-structures](https://github.com/lisp-polymorph/polymorph.data-structures/tree/master/src)
- Another attempt is in [abstract-arrays](https://github.com/digikar99/abstract-arrays/blob/main/specializations.lisp)

**Comment by shamazmazum** [comment]
> I guess one of the main goals here is to write a generic dual type/structure/class with its contents varying from (unsigned-byte 8) all the way up to complex - correct me if I get it wrong.

From `(unsigned-byte 8)` to `real`, but you understand the idea correctly.

OK, thank you for answers. As I understand from `polymorph.data-structures` a solution may be in creating a mapping between parametric types and old plain structures.

**Comment by digikar99** [comment]
Another something if you - or any passers-by - want to wonder about could be about integrating coalton (the types!) itself, given that coalton was actually made for integrating in the rest of the CL ecosystem. Although, at that point, one just might as well use coalton and avoid PF altogether.

**Comment by commander-trashdin** [comment]
Ye, I think I actually can improve my parametric type implementation a bit to reduce what's required to generate.

**Comment by digikar99** [comment]
Okay, some thoughts:

- It is impossible* to have parameterization over an open set of parameter initializations without having a corresponding explosion in the number of concrete objects. In other words, `(pair <type>)` would need an object (a function, a structure, or multiple) for *each* value of `<type>` that is used. This seems at least due to `cl:satisfies` allowing for only single-argument functions. Another caution to be taken while using `cl:satisfies` includes ensuring relevant functions are defined at `:load-time` and not just at `:compile-time`.

- Parameterization over a closed set of parameter values is possible though with those additional functions and/or structures. Two ways include using (i) `cl:satisfies` or (ii) by using `:type` arguments of slots of structures or classes along with inheritance. I find the former lightweight especially when you also want to allow for inheritance as well as for the case of more-than-one parameter, but sometimes it can play rough with `cl:subtypep`; common use cases of `cl:subtypep` can be made to work, but not all. For instance, in the `abstract-arrays` and `dense-arrays` I have put this to use, I have:

```lisp
CL-USER> (subtypep '(dense-arrays:array single-float) 'dense-arrays:array)
T
T
CL-USER> (subtypep '(dense-arrays:array single-float) '(dense-arrays:array double-float))
NIL
NIL
``` 

*I'm still wondering about a `parametric-cl` package that defines its own `deftype`, `type` declaration, and all the things, especially a `satisfies` that can take a function with more-than-one-argument.

**Comment by digikar99** [comment]
Btw, this should now be possible with [extensible-compound-types](https://github.com/digikar99/extensible-compound-types#parametric-types). Although admittedly, it is experimental, and I don't quite know the limitations, barring the fact that it is only intended for concrete types rather than anything (too) abstract.
